update port

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -63,8 +63,8 @@ jobs:
             # echo "Removing unused Docker images..."
             # docker image prune -f
 
-            # Verify if the deployment is successful by checking if the application responds on port 8000
-            echo "Checking if the server is running on port 8000..."
-            nc -zv localhost 5000 || { echo "Deployment failed (port 8000 not open)"; exit 1; }
+            # Verify if the deployment is successful by checking if the application responds on port 8081
+            echo "Checking if the server is running on port 8081..."
+            nc -zv localhost 8081 || { echo "Deployment failed (port 8081 not open)"; exit 1; }
 
-            echo "Deployment successful (server is up on port 8000)"
+            echo "Deployment successful (server is up on port 8081)"
